//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraPayment
    {
        public int Id { get; set; }
        public double Amount { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public string Achievement { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
