//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthSystem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wage
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public double Amount { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Project Project { get; set; }
    }
}
